# Atelier Pandas

## Partie 1 – Series 
### 1. Créer une Serie contenant 4 températures

In [46]:
import pandas as pd
#creation d'une serie pandas qui contient 4 temperatures en degres Celsius
serie = pd.Series([18, 22, 25, 28])
print(serie)

0    18
1    22
2    25
3    28
dtype: int64

### 2. Afficher son index

In [47]:
import pandas as pd
serie = pd.Series([18, 22, 25, 28])
#affiche les indices de la serie
print(serie.index.to_list())

[0, 1, 2, 3]

### 3. Afficher la 1ère valeur

In [48]:
import pandas as pd
serie = pd.Series([18, 22, 25, 28])
#affiche la premiere valeur de la serie
print(serie[0])

18

### 4. Afficher la dernière valeur

In [49]:
import pandas as pd
serie = pd.Series([18, 22, 25, 28])
#affiche la derniere valeur de la serie
print(serie[len(serie)-1])

28

### 5. Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h

In [50]:
import pandas as pd
#creer une serie avec des indices personnalisés
s1 = pd.Series(['18', '22', '25', '28'], index=['12h', '13h', '14h', '15h'])
print(f"serie avec indices personnalisés:\n{s1}\n")
#creer une serie à partir d'un dictionnaire
d = {'12h': 18, '13h': 22, '14h': 25, '15h': 28}
s2 = pd.Series(d)
print(f"serie à partir du dictionnaire:\n{s2}\n")

serie avec indices personnalisés:
12h    18
13h    22
14h    25
15h    28
dtype: str

serie à partir du dictionnaire:
12h    18
13h    22
14h    25
15h    28
dtype: int64

### 6. Afficher la 1ère et la dernière valeur

In [51]:
import pandas as pd
s1 = pd.Series(['18', '22', '25', '28'], index=['12h', '13h', '14h', '15h'])
d = {'12h': 18, '13h': 22, '14h': 25, '15h': 28}
s2 = pd.Series(d)
# accès par position numérique, peu importe le label
print(f"Première valeur de la série avec indice personnalisé: {s1.iloc[0]}")

print(f"Dernière valeur de la série avec indice personnalisé: {s1.iloc[len(s1)-1]}")    

print(f"Première valeur de la série avec dictionnaire: {s2.iloc[0]}")

print(f"Dernière valeur de la série avec dictionnaire: {s2.iloc[len(s2)-1]}")

Première valeur de la série avec indice personnalisé: 18
Dernière valeur de la série avec indice personnalisé: 28
Première valeur de la série avec dictionnaire: 18
Dernière valeur de la série avec dictionnaire: 28

## Partie 2 – DataFrame 
### 1. Créer et afficher le dataframe df_test à partir du dictionnaire

In [52]:
import pandas as pd

data = { 
 "capteur": ["C001", "C002", "C003"], 
 "temperature": [24.5, 25.1, 26.3], 
 "humidite": [65, 67, 70] 
}

df_test = pd.DataFrame(data)
print(df_test)

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

### 2. Importer le dataset mesures_capteurs.csv dans le dataframe df

In [53]:
# importer le dataset mesures_capteurs.csv dans un dataframe pandas
import pandas as pd
df = pd.read_csv("../data/mesures_capteurs.csv")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 3. Afficher les dimensions de df

In [54]:
#afficher les dimensions du dataframe
print(f"Dimensions du dataframe: {df.shape}")

Dimensions du dataframe: (605, 9)

## Partie 3 – Exploration 
### 1. Afficher les premières lignes

In [55]:
#afficher les 5 premières lignes du dataframe
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 2. Afficher les 10 premières lignes

In [56]:
# afficher les 10 premières lignes du dataframe
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

### 3. Afficher les dernières lignes

In [57]:
# afficher les dernières lignes du dataframe
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

### 4. Afficher le nombre de lignes

In [58]:
# afficher le nombre de lignes
print(f"Nombre de lignes: {df.shape[0]}")

Nombre de lignes: 605

### 5. Afficher le nombre de colonnes

In [59]:
# afficher le nombre de colonnes
print(f"Nombre de colonnes: {df.shape[1]}")

Nombre de colonnes: 9

### 6. Afficher les noms des colonnes

In [60]:
# afficher les noms des colonnes
print(f"Noms des colonnes: {df.columns.to_list()}")

Noms des colonnes: ['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature', 'humidite', 'pression', 'consommation', 'etat']

### 7. Afficher les informations générales

In [61]:
#afficher les informations sur le dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 63.0 KB

### 8. Afficher les statistiques descriptives

In [62]:
# afficher les statistiques descriptives du dataframe
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

## Partie 4 – Sélection 
### 1. Sélectionner la colonne "temperature"

In [63]:
# selectioner la colonne temperature
df['temperature']

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

### 2. Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"

In [64]:
#selectionner les colonnes temperature  humidite pression et consommation
df[['temperature', 'humidite', 'pression', 'consommation']]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

### 3. Sélectionner les 5 premières lignes avec loc

In [65]:
# selectionner les 5 premieres lignes avec loc
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 4. Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [66]:
#Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

## Partie 5 – Manipulation des colonnes 
### 1. Ajouter la colonne "temperature_fahrenheit"

In [67]:
#ajouter la colonne "temperature_fahrenheit"
df['temperature_fahrenheit'] = df['temperature'] 
print(df.head())

  id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0     M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1     M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2     M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3     M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4     M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80

   pression  consommation etat  temperature_fahrenheit
0   1008.95        287.28   OK                   25.46
1    993.39        116.20   OK                   24.00
2   1010.32        288.50   OK                   25.82
3   1019.62        136.65   OK                   28.23
4   1016.58        182.62   OK                   20.58

### 2. Ajouter la colonne "niveau_temperature" pour catégoriser la température en "Élevée" (température > 30) ou "Normale". On peut utiliser la méthode where() de numpy

In [68]:
import pandas as pd
import numpy as np

df['niveau_temperature'] = np.where(df['temperature'] > 30, 'élevée', 'normale')
print(df.head())

  id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0     M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1     M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2     M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3     M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4     M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80

   pression  consommation etat  temperature_fahrenheit niveau_temperature
0   1008.95        287.28   OK                   25.46            normale
1    993.39        116.20   OK                   24.00            normale
2   1010.32        288.50   OK                   25.82            normale
3   1019.62        136.65   OK                   28.23            normale
4   1016.58        182.62   OK                   20.58            normale

### 3. Renommer la colonne "humidite" en "humidite_relative"

In [69]:
#renommer une colonne du dataframe
df.rename(columns={"humidite": "humidite_relative"}, inplace=True)
print(df.head())

  id_mesure           date_heure id_capteur batiment  temperature  \
0     M0413  2026-01-22 04:00:00       C005     B002        25.46
1     M0290  2026-01-17 01:00:00       C002     B001        24.00
2     M0077  2026-01-08 04:00:00       C005     B002        25.82
3     M0079  2026-01-08 06:00:00       C007     B003        28.23
4     M0183  2026-01-12 14:00:00       C003     B001        20.58

   humidite_relative  pression  consommation etat  temperature_fahrenheit  \
0              58.06   1008.95        287.28   OK                   25.46
1              79.73    993.39        116.20   OK                   24.00
2              54.47   1010.32        288.50   OK                   25.82
3              69.39   1019.62        136.65   OK                   28.23
4              53.80   1016.58        182.62   OK                   20.58

  niveau_temperature
0            normale
1            normale
2            normale
3            normale
4            normale

### 4. Supprimer la colonne "temperature_fahrenheit"

In [70]:
#supprimer la colonne "temperature_fahrenheit"
import pandas as pd
df.drop("temperature_fahrenheit", axis=1)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,normale
...,...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK,normale
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK,normale
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK,normale
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK,normale
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK,normale

## Partie 6 – Filtrage 
### 1. Récupérer uniquement les lignes telles que température > 30

In [71]:
#recuperer des lignes 
df_temp_elevee = df[df['temperature'] > 30]
print(df_temp_elevee)

    id_mesure           date_heure id_capteur batiment  temperature  \
7       M0132  2026-01-10 11:00:00       C012     B004        31.21
43      M0575  2026-01-28 22:00:00       C011     B004        34.72
47      M0082  2026-01-08 09:00:00       C010     B004        32.46
63      M0064  2026-01-07 15:00:00       C004     B002        31.19
79      M0275  2026-01-16 10:00:00       C011     B004        31.74
88      M0288  2026-01-16 23:00:00       C012     B004        30.06
103     M0311  2026-01-17 22:00:00       C011     B004        30.83
112     M0149  2026-01-11 04:00:00       C005     B002        31.46
118     M0365  2026-01-20 04:00:00       C005     B002        32.90
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
137     M0076  2026-01-08 03:00:00       C004     B002        31.18
145     M0503  2026-01-25 22:00:00       C011     B004        30.57
146     M0118  2026-01-09 21:00:00       C010     B004        30.32
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
168     M0276  2026-01-16 11:00:00       C012     B004        30.39
169     M0546  2026-01-27 17:00:00       C006     B002        32.36
174     M0405  2026-01-21 20:00:00       C009     B003        31.74
210     M0588  2026-01-29 11:00:00       C012     B004        31.51
211     M0370  2026-01-20 09:00:00       C010     B004        33.29
224     M0303  2026-01-17 14:00:00       C003     B001        30.84
243     M0416  2026-01-22 07:00:00       C008     B003        30.16
246     M0312  2026-01-17 23:00:00       C012     B004        30.13
251     M0114  2026-01-09 17:00:00       C006     B002        31.85
257     M0378  2026-01-20 17:00:00       C006     B002        31.99
264     M0191  2026-01-12 22:00:00       C011     B004        30.75
274     M0046  2026-01-06 21:00:00       C010     B004        30.92
280     M0585  2026-01-29 08:00:00       C009     B003        31.30
322     M0120  2026-01-09 23:00:00       C012     B004        30.19
356     M0574  2026-01-28 21:00:00       C010     B004        30.61
362     M0396  2026-01-21 11:00:00       C012     B004        30.57
385     M0126  2026-01-10 05:00:00       C006     B002        30.09
398     M0514  2026-01-26 09:00:00       C010     B004        30.48
401     M0586  2026-01-29 09:00:00       C010     B004        31.44
404     M0598  2026-01-29 21:00:00       C010     B004        30.37
417     M0432  2026-01-22 23:00:00       C012     B004        30.38
437     M0286  2026-01-16 21:00:00       C010     B004        32.16
438     M0558  2026-01-28 05:00:00       C006     B002        32.56
447     M0170  2026-01-12 01:00:00       C002     B001        31.15
488     M0431  2026-01-22 22:00:00       C011     B004        30.14
492     M0552  2026-01-27 23:00:00       C012     B004        30.24
500     M0062  2026-01-07 13:00:00       C002     B001        30.39
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
505     M0268  2026-01-16 03:00:00       C004     B002        30.34
520     M0063  2026-01-07 14:00:00       C003     B001        32.72
541     M0202  2026-01-13 09:00:00       C010     B004        30.86
558     M0346  2026-01-19 09:00:00       C010     B004        30.68

     humidite_relative  pression  consommation    etat  \
7                60.57   1024.64        285.92      OK
43               57.50   1008.94        266.22  ALERTE
47               72.31   1000.42        276.99  ALERTE
63               55.13   1011.04        264.98      OK
79               69.95   1020.79        335.89      OK
88               75.30   1014.47        323.32      OK
103              54.99   1026.47        256.11      OK
112              48.48   1002.75        210.94      OK
118              65.91   1027.28        246.08  ALERTE
129              79.80   1021.96        212.55  ALERTE
137              49.66   1019.91        215.22      OK
145              71.26   1002.88        359.97      OK
146                NaN   1015.78        261.68      OK
165              73.24   1014.36        260.24  ALERTE
168              71.14   1017.79        303.38      OK
169              67.34    998.10        184.89  ALERTE
174              47.23   1015.59        115.79      OK
210              72.49   1018.21        307.97      OK
211              50.43   1009.87        356.76  ALERTE
224              67.98   1020.09        157.99      OK
243              54.00   1012.18        875.00  ERREUR
246              65.68   1009.70        198.65      OK
251              85.77   1013.56        237.21  ALERTE
257              66.32   1013.54        254.67      OK
264              71.35   1018.92        308.66      OK
274              67.19   1009.71        329.78      OK
280              73.35   1021.40        187.98      OK
322              53.58   1013.05        396.90  ALERTE
356              60.73   1022.32        321.75      OK
362              63.47   1017.40        248.36      OK
385              73.95   1007.24        162.39      OK
398              93.57   1015.93        306.24  ALERTE
401              63.10    996.56        271.51      OK
404              64.55    997.31        311.77      OK
417              65.98   1005.48        256.18      OK
437              41.80    996.99        255.56  ALERTE
438              67.77   1016.88        181.51  ALERTE
447              69.20   1016.10        172.49      OK
488              51.02   1007.70        366.53  ALERTE
492              62.06   1009.35        299.69      OK
500              52.13   1004.23        262.66      OK
502              81.51   1026.79        271.92  ERREUR
505              64.23   1011.42        179.84      OK
520              53.28   1010.05        195.37  ALERTE
541              76.00   1011.94        224.01      OK
558              36.33   1010.46        272.59      OK

     temperature_fahrenheit niveau_temperature
7                     31.21             élevée
43                    34.72             élevée
47                    32.46             élevée
63                    31.19             élevée
79                    31.74             élevée
88                    30.06             élevée
103                   30.83             élevée
112                   31.46             élevée
118                   32.90             élevée
129                   33.60             élevée
137                   31.18             élevée
145                   30.57             élevée
146                   30.32             élevée
165                   33.01             élevée
168                   30.39             élevée
169                   32.36             élevée
174                   31.74             élevée
210                   31.51             élevée
211                   33.29             élevée
224                   30.84             élevée
243                   30.16             élevée
246                   30.13             élevée
251                   31.85             élevée
257                   31.99             élevée
264                   30.75             élevée
274                   30.92             élevée
280                   31.30             élevée
322                   30.19             élevée
356                   30.61             élevée
362                   30.57             élevée
385                   30.09             élevée
398                   30.48             élevée
401                   31.44             élevée
404                   30.37             élevée
417                   30.38             élevée
437                   32.16             élevée
438                   32.56             élevée
447                   31.15             élevée
488                   30.14             élevée
492                   30.24             élevée
500                   30.39             élevée
502                   58.70             élevée
505                   30.34             élevée
520                   32.72             élevée
541                   30.86             élevée
558                   30.68             élevée

### 2. Récupérer uniquement les lignes telles que température > 30 et humidité > 70

In [73]:
import pandas as pd
import numpy as np
#recuperer uniquement les lignes et colonnes ciblées
df_filtered = df[(df['temperature'] > 30) & (df['humidite_relative'] > 70)]
print(df_filtered)

    id_mesure           date_heure id_capteur batiment  temperature  \
47      M0082  2026-01-08 09:00:00       C010     B004        32.46
88      M0288  2026-01-16 23:00:00       C012     B004        30.06
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
145     M0503  2026-01-25 22:00:00       C011     B004        30.57
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
168     M0276  2026-01-16 11:00:00       C012     B004        30.39
210     M0588  2026-01-29 11:00:00       C012     B004        31.51
251     M0114  2026-01-09 17:00:00       C006     B002        31.85
264     M0191  2026-01-12 22:00:00       C011     B004        30.75
280     M0585  2026-01-29 08:00:00       C009     B003        31.30
385     M0126  2026-01-10 05:00:00       C006     B002        30.09
398     M0514  2026-01-26 09:00:00       C010     B004        30.48
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
541     M0202  2026-01-13 09:00:00       C010     B004        30.86

     humidite_relative  pression  consommation    etat  \
47               72.31   1000.42        276.99  ALERTE
88               75.30   1014.47        323.32      OK
129              79.80   1021.96        212.55  ALERTE
145              71.26   1002.88        359.97      OK
165              73.24   1014.36        260.24  ALERTE
168              71.14   1017.79        303.38      OK
210              72.49   1018.21        307.97      OK
251              85.77   1013.56        237.21  ALERTE
264              71.35   1018.92        308.66      OK
280              73.35   1021.40        187.98      OK
385              73.95   1007.24        162.39      OK
398              93.57   1015.93        306.24  ALERTE
502              81.51   1026.79        271.92  ERREUR
541              76.00   1011.94        224.01      OK

     temperature_fahrenheit niveau_temperature
47                    32.46             élevée
88                    30.06             élevée
129                   33.60             élevée
145                   30.57             élevée
165                   33.01             élevée
168                   30.39             élevée
210                   31.51             élevée
251                   31.85             élevée
264                   30.75             élevée
280                   31.30             élevée
385                   30.09             élevée
398                   30.48             élevée
502                   58.70             élevée
541                   30.86             élevée