# Atelier Pandas

## Partie 1 – Series 
### 1. Créer une Serie contenant 4 températures

In [9]:
import pandas as pd
#creation d'une serie pandas qui contient 4 temperatures en degres Celsius
serie = pd.Series([18, 22, 25, 28])
print(serie)

0    18
1    22
2    25
3    28
dtype: int64

### 2. Afficher son index

In [11]:
import pandas as pd
serie = pd.Series([18, 22, 25, 28])
#affiche les indices de la serie
print(serie.index.to_list())

[0, 1, 2, 3]

### 3. Afficher la 1ère valeur

In [12]:
import pandas as pd
serie = pd.Series([18, 22, 25, 28])
#affiche la premiere valeur de la serie
print(serie[0])

18

### 4. Afficher la dernière valeur

In [14]:
import pandas as pd
serie = pd.Series([18, 22, 25, 28])
#affiche la derniere valeur de la serie
print(serie[len(serie)-1])

28

### 5. Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h

In [4]:
import pandas as pd
#creer une serie avec des indices personnalisés
s1 = pd.Series(['18', '22', '25', '28'], index=['12h', '13h', '14h', '15h'])
print(f"serie avec indices personnalisés:\n{s1}\n")
#creer une serie à partir d'un dictionnaire
d = {'12h': 18, '13h': 22, '14h': 25, '15h': 28}
s2 = pd.Series(d)
print(f"serie à partir du dictionnaire:\n{s2}\n")

serie avec indices personnalisés:
12h    18
13h    22
14h    25
15h    28
dtype: str

serie à partir du dictionnaire:
12h    18
13h    22
14h    25
15h    28
dtype: int64

### 6. Afficher la 1ère et la dernière valeur

In [3]:
import pandas as pd
s1 = pd.Series(['18', '22', '25', '28'], index=['12h', '13h', '14h', '15h'])
d = {'12h': 18, '13h': 22, '14h': 25, '15h': 28}
s2 = pd.Series(d)
# accès par position numérique, peu importe le label
print(f"Première valeur de la série avec indice personnalisé: {s1.iloc[0]}")

print(f"Dernière valeur de la série avec indice personnalisé: {s1.iloc[len(s1)-1]}")    

print(f"Première valeur de la série avec dictionnaire: {s2.iloc[0]}")

print(f"Dernière valeur de la série avec dictionnaire: {s2.iloc[len(s2)-1]}")

Première valeur de la série avec indice personnalisé: 18
Dernière valeur de la série avec indice personnalisé: 28
Première valeur de la série avec dictionnaire: 18
Dernière valeur de la série avec dictionnaire: 28

## Partie 2 – DataFrame 
### 1. Créer et afficher le dataframe df_test à partir du dictionnaire

In [8]:
import pandas as pd

data = { 
 "capteur": ["C001", "C002", "C003"], 
 "temperature": [24.5, 25.1, 26.3], 
 "humidite": [65, 67, 70] 
}

df_test = pd.DataFrame(data)
print(df_test)

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

### 2. Importer le dataset mesures_capteurs.csv dans le dataframe df

In [11]:
# importer le dataset mesures_capteurs.csv dans un dataframe pandas
import pandas as pd
df = pd.read_csv("../data/mesures_capteurs.csv")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 3. Afficher les dimensions de df

In [12]:
#afficher les dimensions du dataframe
print(f"Dimensions du dataframe: {df.shape}")

Dimensions du dataframe: (605, 9)

## Partie 3 – Exploration 
### 1. Afficher les premières lignes

In [13]:
#afficher les 5 premières lignes du dataframe
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

### 2. Afficher les 10 premières lignes

In [14]:
# afficher les 10 premières lignes du dataframe
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK